### ISSUE TITLE
FOMM seems to crash when selecting New Vegas

### ISSUE THREAD

**Issue by Kyogi** [niveuseverto/fomm#22]
It was working fine yesterday then today when I tried to use it for New Vegas it crashed, according the the text box it looks to be something with checking for updates on FOMODs but heres a crash dump for more info: 

Tuesday, January 13, 2015 - 1:06:01 PM
Fomm 0.14.11.9
OS version: Microsoft Windows NT 6.1.7601 Service Pack 1

SevenZip.SevenZipArchiveException: Invalid archive: open/read error! Is it encrypted and a wrong password was provided?
If your archive is an exotic one, it is possible that SevenZipSharp has no signature for its format and thus decided it is TAR by mistake.
   at SevenZip.SevenZipBase.ThrowException(CallbackBase handler, Exception[] e)
   at SevenZip.SevenZipExtractor.OpenArchive(IInStream archiveStream, ArchiveOpenCallback openCallback)
   at SevenZip.SevenZipExtractor.GetArchiveInfo(Boolean disposeStream)
   at SevenZip.SevenZipExtractor.get_IsSolid()
   at Fomm.PackageManager.Archive.LoadFileIndices()
   at Fomm.PackageManager.Archive..ctor(String p_strPath)
   at Fomm.PackageManager.fomod..ctor(String path, Boolean p_booUseCache)
   at Fomm.PackageManager.Upgrade.UpgradeScanner.Scan()
   at Fomm.Program.Main(String[] args)

EDIT: Ok well I found the culprit it seems the latest mod I installed made that error, removing it from the FOMOD list made FOMM work for New Vegas again, guess theres just certain mods that wont update when FOMM tries to update them but hopefully this will help other FOMM users if they get this same error, all they have to do is remember what mod they installed last.

**Comment by niveuseverto** [comment]
Will make patch to this, Thanks!

**Comment by niveuseverto** [comment]
Released here and on NexusMods latest version. If problem persists, feel free to reopen this issue.
