### ISSUE TITLE
Crashes under windows 10

### ISSUE THREAD

**Issue by snipeswoodland** [niveuseverto/fomm#46]
Hello,
this is my first time posting here so i will try to get you all the info you need.

i just upgraded to win 10 and was gonna install fonv with the tale of two wastelands mod 
then when i opened fomm and wanted to change the settings it just crashed the dump says :

"Sunday, August 2, 2015 - 1:55:57 AM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

i tried the ussual compatibility fixes and modes luanched as admin and nothing seems to fix it maybe a change in the windows code that bugs the program.

**Comment by steelstiletto** [comment]
Commenting to add that I also have this issue on Windows 10. Clicking the settings button crashes the application immediately. Here is my crashdump.txt:

Tuesday, October 6, 2015 - 6:15:00 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
