### ISSUE TITLE
Crash under Windows 10 on update

### ISSUE THREAD

**Issue by BytewaveMLP** [niveuseverto/fomm#47]
Attempting to launch FOMM today brought up an interesting little issue under Windows 10—the program immediately crashes after the dialog for updates is dismissed. The crash dump is as follows:

```
Friday, September 4, 2015 - 6:21:45 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at Fomm.BackgroundWorkerProgressDialog.System.IDisposable.Dispose()
   at Fomm.InstallLogUpgraders.Upgrader.PerformUpgrade()
   at Fomm.InstallLogUpgraders.InstallLogUpgrader.UpgradeInstallLog()
   at Fomm.Program.Main(String[] args)
```

**Comment by BytewaveMLP** [comment]
**Update:** Removing my install log XML file fixed it, as I guessed it probably would, but yknow. I'll leave this bug report here in case it helps in fixing this in the future.
